server.port=${SERVER_PORT}
spring.application.name=relations-service
spring.data.mongodb.database=${DB_NAME}
spring.data.mongodb.uri=mongodb+srv://${DB_USER}:${DB_PASSWORD}@cluster0.cr37uol.mongodb.net/${DB_NAME}
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.topic-name=relation-service-topic
spring.kafka.consumer.group-id=relation-consumer-group